<?php

use Illuminate\Database\Seeder;
use App\Models\Laboratorio;

class LaboratorioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lab = [
           " DENTAURUN ",
           " PORTUGAL ",
           "1 PS ",
           "3M",
           "3M ",
           "3M ESPE",
           "3M ESPE ",
           "A Y B MEDIC ",
           "AALBADENT",
           "ACCESS",
           "ALESSI",
           "ALFER",
           "ALFYMEDIX ",
           "ALKOFARMA ",
           "ALKOFHAR ",
           "ALKOYODO ",
           "ALPLIA - DENT ",
           "AMERICA",
           "AMERICA ",
           "ARAIN ",
           "ARO ",
           "AVAL ",
           "AZDENT",
           "BABYSEC",
           "BAHIA ",
           "B-CORONA",
           "BEIRSODORE",
           "BELUSA ",
           "BESI ",
           "BILBAO ",
           "BIODINAMICA ",
           "BIOSANO ",
           "BIOSEAL ",
           "BIOSYNTEC",
           "BIOTECH ",
           "BONAPHAR ",
           "BONAPHARM",
           "BOTECH",
           "BPM",
           "BRAUN",
           "BRAUN ",
           "BUFALO ",
           "CARESTREAM",
           "CARESTREM ",
           "CAVO ",
           "CHAMPION ",
           "CHEEK RETRACTOR ",
           "CHINO ",
           "CIDRAS ",
           "CIRUJIA PERUANA",
           "CITOGLASS ",
           "CITOTEST ",
           "C-K GOCT",
           "CKF",
           "COLGATE ",
           "COMIWA ",
           "CONFIDENT ",
           "CONTINENTAL ",
           "COPPON",
           "CRAMBERRY ",
           "CURITAS ",
           "D Y R ",
           "DAGO ",
           "DANY",
           "DANY ",
           "DECO ",
           "DENSPLY",
           "DENSPLY ",
           "DENTAURUM",
           "DENTITO ",
           "DENTO ",
           "DENTORIUM ",
           "DENTS ",
           "DESTAFAR ",
           "DIAMOND ",
           "DIMEDA GERMANY ",
           "DIXON ",
           "DURAMED",
           "ECG ",
           "ECOMAX ",
           "ECONOMY ",
           "EGO ",
           "ELEGANTE",
           "ELITE ",
           "ENDOFILL",
           "ENDOGLOVE ",
           "ENDOMEDIC ",
           "ESLIMEDIC",
           "ETCHANGEL ",
           "EUFAR ",
           "EUGENOL ",
           "EVE",
           "FARMAGAL",
           "FARMAGAL ",
           "FARMAINDUSTRIA",
           "FARVET",
           "FAVA ",
           "FERYANY ",
           "FG",
           "FG ",
           "FGM",
           "FIRTS CLASS",
           "GALAXY",
           "GALBAN",
           "GALENO",
           "GALENO ",
           "GAMED ",
           "GENFAR",
           "GERMANY ",
           "GIARDINO ",
           "GLASS ",
           "GRANBERRY ",
           "GRANVERRY ",
           "GREETMED ",
           "GSK",
           "GUILLETTE ",
           "HAIILU ",
           "HANDLE 59",
           "HEPIDEFARMA ",
           "HI- MED",
           "HI-MED",
           "HIPOCAMPO ",
           "HUGGIES ",
           "HYGEDENT ",
           "IMEC ",
           "IMPORTADO",
           "IMPORTADO ",
           "IMPROVE ",
           "INDIRAL ",
           "INDUQUIMICA ",
           "INDUSTRIA ARGENTINA ",
           "INMEDENTS ",
           "INTRAVEN",
           "IQFARMA",
           "IQFARMA ",
           "ISOLAB",
           "IVOCLAR ",
           "JHONSON ",
           "JPS",
           "JPS ",
           "JUMILSAN ",
           "KD-JECT ",
           "KEYSTONE",
           "KIP ",
           "KIT ",
           "KOLYNOS ",
           "KOTEX ",
           "KYNTEL ",
           "LABON",
           "LABOT ",
           "LANCIER ",
           "LASCOD",
           "LASCOD ",
           "LEVEL ",
           "LOYLA ",
           "LUSA ",
           "M Y U ",
           "MAC",
           "MANCHELEY - NAGEL ",
           "MAQUIRA ",
           "MASTER DENT ",
           "MAVER ",
           "MCG",
           "MDT",
           "MDT ",
           "MEDESY ",
           "MEDIANCE ",
           "MEDICAL",
           "MEDIFARMA ",
           "MEDOCK",
           "MENZHER ",
           "MERCK ",
           "MICRODONT ",
           "MISAL ",
           "MISAWA ",
           "MKT PHARMA",
           "MOALTH ",
           "MONCLER ",
           "MONTGROUP ",
           "MORELLI ",
           "N.S.P.",
           "NACIONAL",
           "NACIONAL ",
           "NALLONDI ",
           "NATURGEN",
           "NBS ",
           "NENOMMA",
           "NEOGLOVES ",
           "NEW FUERTE ",
           "NEW STETIC",
           "NEWCAINA",
           "NIPRO",
           "NIPRO ",
           "NITI-KAHIA",
           "NIVEA ",
           "NORDENT ",
           "NORDIN ",
           "NOSOTRAS ",
           "NOWCAINA ",
           "NSK ",
           "NUTRIBELLA 10",
           "O LEOS ",
           "ODONTOCAINA",
           "OLYMPIC",
           "OLYMPIC ",
           "OLYMPIC PLUS ",
           "OML ",
           "ONE-JECT",
           "ORAL -B ",
           "ORION ",
           "OTARVASQ",
           "PAMPERS ",
           "PENTALLOY ",
           "PERFACTIN ",
           "PERFEX",
           "PERFEX ",
           "PHAKM",
           "PHARMAGEN ",
           "PHARMED",
           "PLENITUD",
           "PLENITUD ",
           "PLEXDON ",
           "PONDS ",
           "PORTUGAL ",
           "PORUCRYL ",
           "PRIMA CLASSIC",
           "PRIME-DONT ",
           "PRO GLASS ",
           "PROMED",
           "PROQUIDENT ",
           "PROTHOPLAST ",
           "PYREX",
           "PYREX ",
           "QARTZ",
           "Q-MEDIC",
           "Q-MEDIC ",
           "QUILAB",
           "QUIROFANO ",
           "REESMILE ",
           "REXONA",
           "RIESTER ",
           "RIMER-DENT ",
           "ROCHE",
           "ROCHE ",
           "ROFER",
           "ROKER",
           "RYNCO",
           "SAMEX ",
           "SANDERSON ",
           "SANOFI",
           "SAONA ",
           "SEGURIMAX ",
           "SEGURIMAXX",
           "SEPLYSI ",
           "SHERFARMA ",
           "SHICK ",
           "SHINE ",
           "SHWARZOKPK",
           "SIEGFRIED",
           "SIGMA",
           "SMIC ",
           "SONY ",
           "STAR ROLLS",
           "STAR WAX ",
           "STAYFREE",
           "STERIMAXX ",
           "SUCTION CLEAN ",
           "SWE DENT ",
           "TAGUM ",
           "TDM ",
           "TEVA ",
           "THOMAS ",
           "TINTADO",
           "TISEN ",
           "TOBOOM ",
           "TOPGEL ",
           "TOPWAX",
           "TOPWAX ",
           "TOU",
           "ULTRA - SPEED ",
           "ULTRA-FINE ",
           "ULTRASOFT ",
           "UNILENE ",
           "UNILEVER ",
           "UNIVERSAL",
           "UNIVERSAL ",
           "URITEL",
           "VAICRIL ",
           "VICK ",
           "VITACROM ",
           "VITACRON",
           "VITACRYL",
           "VITACRYL ",
           "VITAFOIL ",
           "VITALIS ",
           "VITALLOY",
           "VITALLOY ",
           "VITALOY",
           "VIVADENT ",
           "VOCO",
           "WHATMAN ",
           "WHITENEES PERFECT ",
           "XYLOSTESIN ",
           "YANCHED ",
           "ZHERMACK",
           "-"
        ];
        //$labUniq = array_unique($lab);
        
        for ($i=0; $i < count($lab); $i++) {
            Laboratorio::create([
                'nombre'=>strtoupper($lab[$i]),
                'descripcion'=>strtoupper("$i"),
                'condicion' => 1
            ]);
        }
    }
}
