<?php

use Illuminate\Database\Seeder;
use App\Models\Laboratorio;

class LaboratorioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lab = [
            "3M",
            "3M ESPE",
            "A Y B MEDIC",
            "ACCESS",
            "ALBADENT",
            "ALCIMASK",
            "ALESSI",
            "ALFER",
            "ALFYMEDIX",
            "ALKHOFAR",
            "ALKOFARMA",
            "ALPK2",
            "ALPLIA - DENT",
            "AMERICA",
            "ARAIN",
            "AVAL",
            "AZDENT",
            "BABYSEC",
            "BAHIA",
            "B-CORONA",
            "BEIRSODORE",
            "BELUSA",
            "BESI",
            "BILBAO",
            "BIO ZIM",
            "BIOAR",
            "BIODINAMICA",
            "BIOLIFE",
            "BIOPROTECH",
            "BIOSEAL",
            "BIOTECH",
            "BLUSA",
            "BONAPHAR",
            "BOTECH",
            "BRAUN",
            "BUFALO",
            "BUK",
            "CARESTREM",
            "CHAMPION",
            "CHEEK RETRACTOR",
            "CHEMICAL",
            "CHINO",
            "CHROMATIC",
            "CIDRAS",
            "CIRUGIA PERUANA",
            "CITOGLASS",
            "CITOPLAST",
            "CITOTEST",
            "C-K GOCT",
            "CKF",
            "COLGATE",
            "COMIDENT",
            "CONFIDENT",
            "CONTINENTAL",
            "COPPON",
            "CRAMBERRY",
            "CREATIVE",
            "CUREBAND",
            "D LEOS",
            "DAGO",
            "DANY",
            "DECO",
            "DENSPLY",
            "DENTAURUM",
            "DENTITO",
            "DENTO",
            "DENTORIUM",
            "DENTSPLY",
            "DESTAFAR",
            "DIAMOND",
            "DIMEDA GERMANY",
            "DIXON",
            "DNT",
            "DRAGON",
            "DRIL",
            "DROPESAC",
            "DURAMED",
            "DURATONE",
            "DURUMIX",
            "ECONOMY",
            "EGO",
            "ELECTROLIGHT",
            "ELEGANTE",
            "ELITE",
            "ENDOFILL",
            "ENDOGLOVE",
            "ENDOMEDIC",
            "ESLIMEDIC",
            "ETIQUET",
            "EUFAR",
            "EUGENOL",
            "EVE",
            "FABRIMEDIC",
            "FARMAGAL",
            "FARMAINDUSTRIA",
            "FARVET",
            "FAVA",
            "FDA",
            "FERYANY",
            "FGM",
            "FIRTS CLASS",
            "GALATI",
            "GALBAN",
            "GALENO",
            "GAMED",
            "GENFAR",
            "GENTS",
            "GERMANY",
            "GIARDINO",
            "GLASS",
            "GP PHARM",
            "GRANVERRY",
            "GREETMED",
            "GRNFAR",
            "GS",
            "GSK",
            "GUILLETTE",
            "HAIILU",
            "HANDLE 59",
            "HCG",
            "HI-MED",
            "HIPOCAMPO",
            "HUGGIES",
            "IMEC",
            "IMPORTADO",
            "INDIRAL",
            "INDUQUIMICA",
            "INDUSTRIA ARGENTINA",
            "IQ MEDIC",
            "IQFARMA",
            "ISOLAB",
            "IVOCLAR",
            "IVOSTAR",
            "JPS",
            "JUMILSAN",
            "KAVO",
            "KEYSTONE",
            "KIT",
            "KOLYNOS",
            "KOTEX",
            "KURIWAX",
            "KYNTEL",
            "LANCIER",
            "LASCOD",
            "LEVEL",
            "LIDA",
            "LOYLA",
            "LUBRIDENT",
            "LUSA",
            "M Y U",
            "MAC",
            "MANCHELEY - NAGEL",
            "MAQUIRA",
            "MASTER DENT",
            "MAVER",
            "MDT",
            "MEDESY",
            "MEDIANCE",
            "MEDICAL",
            "MEDIFARMA",
            "MEDIKIT",
            "MEDOCK",
            "MENZHER",
            "MERCK",
            "MERHEJE",
            "MICRODONT",
            "MISAWA",
            "MOALTH",
            "MONCLER",
            "MONTGROUP",
            "MORELLI",
            "N.S.P.",
            "NACIONAL",
            "NALLONDI",
            "NATURGEN",
            "NBS",
            "NEKO",
            "NENOMMA",
            "NEOGLOVES",
            "NEW STETIC",
            "NEWCAINA",
            "NEWSTETIC",
            "NIPRO",
            "NITI-KAHIA",
            "NIVEA",
            "NON-WOVER SPONGAS",
            "NORDIN",
            "NOSOTRAS",
            "NOVA",
            "NSK",
            "NUTRIBELLA 10",
            "O LEOS",
            "OML",
            "ONE-JECT",
            "ORAL -B",
            "ORION",
            "ORTOCLAS",
            "ORTOLUX",
            "OTARVASQ",
            "P&G",
            "PAMPERS",
            "PENTALLOY",
            "PERFECTIN",
            "PERFEX",
            "PHARMAGEM",
            "PHARMAGEN",
            "PHARMED",
            "PLENITUD",
            "PLEXDON",
            "PONDS",
            "PORTUGAL",
            "PORUCRYL",
            "PRIMA CLASSIC",
            "PRIME-DENT",
            "PRO GLASS",
            "PROMED",
            "PROQUIDENT",
            "PROTHOPLAST",
            "PRYMA",
            "PYREX",
            "QARTZ",
            "Q-MEDIC",
            "QUILAB",
            "QUIROFANO",
            "REESMILE",
            "REUTER",
            "RIESTER",
            "RIMER-DENT",
            "ROCHE",
            "ROKER",
            "RYNCO",
            "SAMEX",
            "SANDERSON",
            "SANOFI",
            "SAONA",
            "SCHICK",
            "SEGURIMAXX",
            "SEXS",
            "SHERFARMA",
            "SHINE",
            "SHWARZOKPK",
            "SIEGFRIED",
            "SIGMA",
            "SLIDE",
            "SMIC",
            "SONY",
            "STANDENT",
            "STAR ROLLS",
            "STAR WAX",
            "STARDENT",
            "STAYFREE",
            "SUAVE",
            "SUCTION CLEAN",
            "SWE DENT",
            "SWISS DENTAL",
            "TAGUM",
            "TDM",
            "TELA",
            "TEVA",
            "THOMAS",
            "TISEN",
            "TOBOOM",
            "TOPGEL",
            "TOPWAX",
            "TOU",
            "ULTRA - SPEED",
            "ULTRA-FINE",
            "ULTRASOFT",
            "UNILENE",
            "UNILEVER",
            "UNIPIL 1",
            "UNIVERSAL",
            "URITEL",
            "VAICRIL",
            "VENOJET",
            "VICK",
            "VITA",
            "VITACRON",
            "VITACRYL",
            "VITAFOIL",
            "VITALIS",
            "VITALLOY",
            "VIVADENT",
            "VOCO",
            "WHATMAN",
            "WHITENEES PERFECT",
            "X-MEDIC",
            "XYLESTESIN",
            
        ];
        //$labUniq = array_unique($lab);
        
        for ($i=0; $i < count($lab); $i++) {
            Laboratorio::create([
                'nombre'=>strtoupper($lab[$i]),
                'descripcion'=>strtoupper("$i"),
                'condicion' => 1
            ]);
        }
    }
}
